# The URL the site will be built for
base_url = "https://compfinance-book.netlify.com"
title = "Handbook of Computational Finance"
description = "Category-Theoretical & AI-driven Approaches to modern computational finance - combining mathematical rigor with practical applications."

# The default language; used in feeds and search index
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to generate a feed file for the site
generate_feeds = true

# When set to "true", the generated HTML files are minified.
minify_html = false

# The taxonomies to be rendered for the site and their configuration.
taxonomies = [
  {name = "authors"},
]

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = false
# Whether to include the rendered content of the page/section in the index
include_content = true

[markdown]
# Whether to do syntax highlighting.
highlight_code = true

[extra]
# Put all your custom variables here
author = "Serge Youmbi"
github = "https://github.com/sergeyoumbi"
twitter = "https://twitter.com/sergeyoumbi"
email = "serge.youms56@gmail.com"
ganalytics = ""  # Google Analytics code

# If running on netlify.app site, set to true
is_netlify = true

# Set HTML file language
language_code = "en-US"

# Set theme-color meta tag for Chrome browser
theme_color = "#00d9ff"

# More about site's title
title_separator = "|"
title_addition = "Category-Theoretical & AI-driven Approaches"

# Set date format in blog publish metadata
timeformat = "%Y-%m-%d %H:%M:%S"
timezone = "UTC"

# Edit page on repository or not
edit_page = false
docs_repo = "https://github.com/sergeoumbi/compfinance-book"
repo_branch = "main"

## Math settings
# Enable math support globally for a finance/quant book
math = true
library = "katex"

## Open Graph + Twitter Cards
[extra.open]
enable = true
# this image will be used as fallback if a page has no image of its own
image = "compfinance-og.png"
twitter_site = "sergeyoumbi"
twitter_creator = "sergeyoumbi"
facebook_author = ""
facebook_publisher = ""
og_locale = "en_US"

## JSON-LD
[extra.schema]
type = "Organization"
logo = "logo-compfinance.png"
twitter = "https://twitter.com/sergeyoumbi"
linked_in = "https://linkedin.com/in/sergeyoumbi"
github = "https://github.com/sergeyoumbi"
section = "chapters"
## Sitelinks Search Box
site_links_search_box = false


[[extra.menu.social]]
name = "Twitter"
pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-twitter"><path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path></svg>'
url = "https://twitter.com/sergeyoumbi"
weight = 10

[[extra.menu.social]]
name = "GitHub"
pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>'
url = "https://github.com/sergeyoumbi"
post = "v1.0.0"
weight = 20

[[extra.menu.social]]
name = "LinkedIn"
pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-linkedin"><path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z"></path><rect x="2" y="9" width="4" height="12"></rect><circle cx="4" cy="4" r="2"></circle></svg>'
url = "https://linkedin.com/in/sergeyoumbi"
weight = 30

# Footer contents
[extra.footer]
info = 'Handbook of Computational Finance | Category-Theoretical & AI-driven Approaches'

[[extra.footer.nav]]
name = "Privacy"
url = "/privacy-policy/"
weight = 10

[[extra.footer.nav]]
name = "Resources"
url = "/resources/"
weight = 20

[[extra.footer.nav]]
name = "Contact"
url = "/author/"
weight = 30
