# The URL the site will be built for
base_url = "https://cat4dnn.github.io/visualcategorytheory"
title = "Visual Category Theory"
description = "An intuitive, visual journey through category theory - from objects and morphisms to monads and adjunctions. Interactive diagrams, GSAP animations, and practical examples for programmers, mathematicians, and curious minds."

# The default language; used in feeds and search index
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to generate a feed file for the site
generate_feeds = true

# When set to "true", the generated HTML files are minified.
minify_html = false

# The taxonomies to be rendered for the site and their configuration.
taxonomies = [
  {name = "authors"},
  {name = "tags"},
]

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = false
# Whether to include the rendered content of the page/section in the index
include_content = true

[markdown]
# Whether to do syntax highlighting.
highlight_code = true

[extra]
# Put all your custom variables here
author = "Serge Youmbi"
github = "https://github.com/sergeyoumbi"
twitter = "https://twitter.com/CatDNN"
youtube = "https://youtube.com/channel/UCtQUTq8fvWQAQKx72HLdzLw"
github_project = "https://github.com/Cat4DNN/visual-category-theory"
email = "serge.youms56@gmail.com"
ganalytics = ""  # Google Analytics code

# If running on netlify.app site, set to true
is_netlify = false

# Set HTML file language
language_code = "en-GB"

# Set theme-color meta tag for Chrome browser
theme_color = "#6366f1"

# More about site's title
title_separator = "|"
title_addition = "Interactive Visual Learning"

# Set date format in blog publish metadata
timeformat = "%Y-%m-%d %H:%M:%S"
timezone = "UTC"

# Edit page on repository or not
edit_page = true
docs_repo = "https://github.com/Cat4DNN/visual-category-theory"
repo_branch = "main"

## Math settings
# Enable math support globally - essential for category theory
math = true
library = "katex"

# Enable GSAP animations
gsap_enabled = true

## Open Graph + Twitter Cards
[extra.open]
enable = true
# this image will be used as fallback if a page has no image of its own
image = "visual-category-theory-og.png"
twitter_site = "CatDNN"
twitter_creator = "CatDNN"
facebook_author = ""
facebook_publisher = ""
og_locale = "en_GB"

## JSON-LD
[extra.schema]
type = "Organization"
logo = "logo-category-theory.png"
twitter = "https://twitter.com/CatDNN"
linked_in = "https://linkedin.com/in/sergeyoumbi"
youtube = "https://youtube.com/channel/UCtQUTq8fvWQAQKx72HLdzLw"
github = "https://github.com/sergeyoumbi"
section = "concepts"
## Sitelinks Search Box
site_links_search_box = false


[[extra.menu.social]]
name = "Twitter"
pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-twitter"><path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path></svg>'
url = "https://twitter.com/CatDNN"
weight = 10

[[extra.menu.social]]
name = "YouTube"
pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-youtube"><path d="M22.54 6.42a2.78 2.78 0 0 0-1.94-2C18.88 4 12 4 12 4s-6.88 0-8.6.46a2.78 2.78 0 0 0-1.94 2A29 29 0 0 0 1 11.75a29 29 0 0 0 .46 5.33A2.78 2.78 0 0 0 3.4 19c1.72.46 8.6.46 8.6.46s6.88 0 8.6-.46a2.78 2.78 0 0 0 1.94-2 29 29 0 0 0 .46-5.25 29 29 0 0 0-.46-5.33z"></path><polygon points="9.75 15.02 15.5 11.75 9.75 8.48 9.75 15.02"></polygon></svg>'
url = "https://youtube.com/channel/UCtQUTq8fvWQAQKx72HLdzLw"
weight = 15

[[extra.menu.social]]
name = "GitHub"
pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>'
url = "https://github.com/Cat4DNN/visual-category-theory"
post = "v1.0.0"
weight = 20

[[extra.menu.social]]
name = "LinkedIn"
pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-linkedin"><path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z"></path><rect x="2" y="9" width="4" height="12"></rect><circle cx="4" cy="4" r="2"></circle></svg>'
url = "https://linkedin.com/in/sergeyoumbi"
weight = 30

# Footer contents
[extra.footer]
info = 'Visual Category Theory | Interactive Learning for the Curious Mind'

[[extra.footer.nav]]
name = "Privacy"
url = "/privacy-policy/"
weight = 10

[[extra.footer.nav]]
name = "Resources"
url = "/resources/"
weight = 20

[[extra.footer.nav]]
name = "References"
url = "/references/"
weight = 25

[[extra.footer.nav]]
name = "Contact"
url = "/author/"
weight = 30
